drop table user if exists;
create table user (
  user_id integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  username varchar(50) not null,
  email varchar(50) not null,
  pw varchar(255) not null
);

drop table feed if exists;
create  table feed (
  feed_id integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  user_id integer not null,
  feedName varchar(160) not null,
  link varchar(160) not null,
);